### Get All Venues
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Venues

### Get All Events
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Events

### Published Events
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Events?$filter=status eq 'Published'

### Events Ordered By Ticket Price
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Events?$orderby=ticketPrice desc

### All Speakers
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Speakers

### Top Rated Speakers
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Speakers?$orderby=rating desc

### Event Speakers Mapping
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/EventSpeakers

### Registrations
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Registrations

### Confirmed Registrations
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Registrations?$filter=status eq 'Confirmed'

### Feedback
GET https://port4004-workspaces-ws-76zvt.ap21.trial.applicationstudio.cloud.sap/odata/v4/event/Feedback